import type { ThemeInspirationPalette, ThemePreset } from "./types";

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "default",
    name: "现代极简",
    englishName: "Mastra Clean",
    category: "modern",
    categoryLabel: "现代极简",
    description: "基于 Mastra 官方设计规范的高性能极简风格，优雅微阴影与多层圆角体系。",
    registrySource: "official",
    styleKey: "default",
    light: {
      background: "#ffffff",
      foreground: "#171717",
      card: "#ffffff",
      cardForeground: "#171717",
      popover: "#ffffff",
      popoverForeground: "#171717",
      primary: "#171717",
      primaryForeground: "#fafafa",
      secondary: "#f5f5f5",
      secondaryForeground: "#171717",
      muted: "#f5f5f5",
      mutedForeground: "#737373",
      accent: "#f5f5f5",
      accentForeground: "#171717",
      destructive: "#dc2626",
      destructiveForeground: "#fafafa",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#a3a3a3",
      sidebar: "#fafafa",
      sidebarForeground: "#171717",
      sidebarPrimary: "#171717",
      sidebarPrimaryForeground: "#fafafa",
      sidebarAccent: "#f5f5f5",
      sidebarAccentForeground: "#171717",
      sidebarBorder: "#e5e5e5",
    },
    dark: {
      background: "#121212",
      foreground: "#fafafa",
      card: "#18181b",
      cardForeground: "#fafafa",
      popover: "#18181b",
      popoverForeground: "#fafafa",
      primary: "#fafafa",
      primaryForeground: "#121212",
      secondary: "#262626",
      secondaryForeground: "#fafafa",
      muted: "#262626",
      mutedForeground: "#a3a3a3",
      accent: "#262626",
      accentForeground: "#fafafa",
      destructive: "#ef4444",
      destructiveForeground: "#fafafa",
      border: "#27272a",
      input: "#27272a",
      ring: "#71717a",
      sidebar: "#18181b",
      sidebarForeground: "#fafafa",
      sidebarPrimary: "#3b82f6",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#27272a",
      sidebarAccentForeground: "#fafafa",
      sidebarBorder: "#27272a",
    },
    geometry: {
      radius: 10,
      borderWidth: 1,
      shadowDepth: 0,
    },
  },
  {
    id: "boldkit",
    name: "BoldKit 新粗野",
    englishName: "BoldKit Brutalism",
    category: "brutalism",
    categoryLabel: "粗野主义",
    description: "极具视觉张力的新粗野主义体系，以纯黑厚重描边、立体实体硬阴影和高饱和亮橙为代表。",
    registrySource: "@boldkit",
    styleKey: "boldkit",
    light: {
      background: "#fefcf6",
      foreground: "#09090b",
      card: "#ffffff",
      cardForeground: "#09090b",
      popover: "#ffffff",
      popoverForeground: "#09090b",
      primary: "#ff5400",
      primaryForeground: "#ffffff",
      secondary: "#ffe5d0",
      secondaryForeground: "#09090b",
      muted: "#f5eedc",
      mutedForeground: "#52525b",
      accent: "#ffc837",
      accentForeground: "#09090b",
      destructive: "#e11d48",
      destructiveForeground: "#ffffff",
      border: "#09090b",
      input: "#09090b",
      ring: "#ff5400",
      sidebar: "#faf3e0",
      sidebarForeground: "#09090b",
      sidebarPrimary: "#ff5400",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#ffe5d0",
      sidebarAccentForeground: "#09090b",
      sidebarBorder: "#09090b",
    },
    dark: {
      background: "#121214",
      foreground: "#f4f4f5",
      card: "#1a1a1e",
      cardForeground: "#f4f4f5",
      popover: "#1a1a1e",
      popoverForeground: "#f4f4f5",
      primary: "#ff6b2b",
      primaryForeground: "#ffffff",
      secondary: "#27272a",
      secondaryForeground: "#f4f4f5",
      muted: "#1c1c1f",
      mutedForeground: "#a1a1aa",
      accent: "#ffd043",
      accentForeground: "#09090b",
      destructive: "#fb7185",
      destructiveForeground: "#121214",
      border: "#ff6b2b",
      input: "#ff6b2b",
      ring: "#ff6b2b",
      sidebar: "#0b0b0d",
      sidebarForeground: "#f4f4f5",
      sidebarPrimary: "#ff6b2b",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#27272a",
      sidebarAccentForeground: "#f4f4f5",
      sidebarBorder: "#3f3f46",
    },
    geometry: {
      radius: 6,
      borderWidth: 2,
      shadowDepth: 3,
    },
  },
  {
    id: "neobrutalism",
    name: "NeoBrutalism 经典",
    englishName: "Classic NeoBrutalism",
    category: "brutalism",
    categoryLabel: "粗野主义",
    description: "经典新粗野主义，0 弧度锐角几何、2px 纯黑外边框、4px 硬阴影与赛博柠檬黄、霓虹青撞色。",
    registrySource: "@neobrutalism",
    styleKey: "neobrutalism",
    light: {
      background: "#fffdfa",
      foreground: "#000000",
      card: "#ffffff",
      cardForeground: "#000000",
      popover: "#ffffff",
      popoverForeground: "#000000",
      primary: "#facc15",
      primaryForeground: "#000000",
      secondary: "#a5f3fc",
      secondaryForeground: "#000000",
      muted: "#f4f4eb",
      mutedForeground: "#3f3f46",
      accent: "#f472b6",
      accentForeground: "#000000",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#000000",
      input: "#000000",
      ring: "#000000",
      sidebar: "#fdf8e6",
      sidebarForeground: "#000000",
      sidebarPrimary: "#000000",
      sidebarPrimaryForeground: "#facc15",
      sidebarAccent: "#fef08a",
      sidebarAccentForeground: "#000000",
      sidebarBorder: "#000000",
    },
    dark: {
      background: "#09090b",
      foreground: "#ffffff",
      card: "#131316",
      cardForeground: "#ffffff",
      popover: "#131316",
      popoverForeground: "#ffffff",
      primary: "#facc15",
      primaryForeground: "#000000",
      secondary: "#164e63",
      secondaryForeground: "#67e8f9",
      muted: "#18181b",
      mutedForeground: "#a1a1aa",
      accent: "#831843",
      accentForeground: "#f472b6",
      destructive: "#f87171",
      destructiveForeground: "#09090b",
      border: "#facc15",
      input: "#facc15",
      ring: "#facc15",
      sidebar: "#050507",
      sidebarForeground: "#ffffff",
      sidebarPrimary: "#facc15",
      sidebarPrimaryForeground: "#000000",
      sidebarAccent: "#27272a",
      sidebarAccentForeground: "#facc15",
      sidebarBorder: "#3f3f46",
    },
    geometry: {
      radius: 0,
      borderWidth: 2,
      shadowDepth: 4,
    },
  },
  {
    id: "retroui",
    name: "RetroUI 复古粗野",
    englishName: "Retro Modern Brutalism",
    category: "brutalism",
    categoryLabel: "粗野主义",
    description: "融合 90 年代报纸排版与极客终端质感，复古琥珀橙、羊皮纸暖底色与粗粝外框。",
    registrySource: "@retroui",
    styleKey: "retroui",
    light: {
      background: "#faf6ee",
      foreground: "#1c1917",
      card: "#ffffff",
      cardForeground: "#1c1917",
      popover: "#ffffff",
      popoverForeground: "#1c1917",
      primary: "#d97706",
      primaryForeground: "#ffffff",
      secondary: "#e7dfd3",
      secondaryForeground: "#1c1917",
      muted: "#ece5d8",
      mutedForeground: "#78716c",
      accent: "#84cc16",
      accentForeground: "#1c1917",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      border: "#1c1917",
      input: "#1c1917",
      ring: "#d97706",
      sidebar: "#f3ecde",
      sidebarForeground: "#1c1917",
      sidebarPrimary: "#d97706",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e4dac9",
      sidebarAccentForeground: "#1c1917",
      sidebarBorder: "#1c1917",
    },
    dark: {
      background: "#161311",
      foreground: "#faf6ee",
      card: "#201b17",
      cardForeground: "#faf6ee",
      popover: "#201b17",
      popoverForeground: "#faf6ee",
      primary: "#f59e0b",
      primaryForeground: "#161311",
      secondary: "#2a2420",
      secondaryForeground: "#faf6ee",
      muted: "#221c18",
      mutedForeground: "#a8a29e",
      accent: "#a3e635",
      accentForeground: "#161311",
      destructive: "#ef4444",
      destructiveForeground: "#161311",
      border: "#786b59",
      input: "#786b59",
      ring: "#f59e0b",
      sidebar: "#100e0c",
      sidebarForeground: "#faf6ee",
      sidebarPrimary: "#f59e0b",
      sidebarPrimaryForeground: "#161311",
      sidebarAccent: "#241f1a",
      sidebarAccentForeground: "#faf6ee",
      sidebarBorder: "#443b32",
    },
    geometry: {
      radius: 4,
      borderWidth: 2,
      shadowDepth: 3,
    },
  },
  {
    id: "saaskit",
    name: "SaaSKit 柔和粗野",
    englishName: "SaaSKit Soft Brutal",
    category: "soft_brutalism",
    categoryLabel: "柔和粗野",
    description: "专为现代化高质感 SaaS 打造的柔和粗野主义，圆润大边角、克制深色轮廓与电光靛蓝。",
    registrySource: "@saaskit",
    styleKey: "saaskit",
    light: {
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      primary: "#4f46e5",
      primaryForeground: "#ffffff",
      secondary: "#e0e7ff",
      secondaryForeground: "#3730a3",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      accent: "#06b6d4",
      accentForeground: "#ffffff",
      destructive: "#e11d48",
      destructiveForeground: "#ffffff",
      border: "#0f172a",
      input: "#0f172a",
      ring: "#4f46e5",
      sidebar: "#f1f5f9",
      sidebarForeground: "#0f172a",
      sidebarPrimary: "#4f46e5",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e2e8f0",
      sidebarAccentForeground: "#0f172a",
      sidebarBorder: "#0f172a",
    },
    dark: {
      background: "#090d16",
      foreground: "#f8fafc",
      card: "#111827",
      cardForeground: "#f8fafc",
      popover: "#111827",
      popoverForeground: "#f8fafc",
      primary: "#6366f1",
      primaryForeground: "#ffffff",
      secondary: "#1e1b4b",
      secondaryForeground: "#e0e7ff",
      muted: "#131b2e",
      mutedForeground: "#94a3b8",
      accent: "#22d3ee",
      accentForeground: "#090d16",
      destructive: "#f43f5e",
      destructiveForeground: "#ffffff",
      border: "#334155",
      input: "#334155",
      ring: "#6366f1",
      sidebar: "#060910",
      sidebarForeground: "#f8fafc",
      sidebarPrimary: "#6366f1",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#1e293b",
      sidebarAccentForeground: "#f8fafc",
      sidebarBorder: "#334155",
    },
    geometry: {
      radius: 10,
      borderWidth: 1.5,
      shadowDepth: 3,
    },
  },
];

export const THEME_INSPIRATIONS: ThemeInspirationPalette[] = [
  {
    id: "cyber-yellow",
    name: "赛博柠檬",
    description: "纯黑边框与明烈电光黄",
    primary: "#facc15",
    secondary: "#fef08a",
    accent: "#38bdf8",
    border: "#000000",
  },
  {
    id: "blaze-orange",
    name: "烈焰赤橙",
    description: "高张力活力热烈橙",
    primary: "#ff5400",
    secondary: "#ffe5d0",
    accent: "#ffc837",
    border: "#09090b",
  },
  {
    id: "neon-pink",
    name: "泡泡糖粉",
    description: "潮酷活泼的霓虹桃粉",
    primary: "#f43f5e",
    secondary: "#fce7f3",
    accent: "#a855f7",
    border: "#000000",
  },
  {
    id: "terminal-green",
    name: "极客荧绿",
    description: "黑客复古终端荧光绿",
    primary: "#22c55e",
    secondary: "#dcfce7",
    accent: "#06b6d4",
    border: "#09090b",
  },
  {
    id: "retro-amber",
    name: "复古琥珀",
    description: "经典 90 年代暖木与琥珀",
    primary: "#d97706",
    secondary: "#fef3c7",
    accent: "#84cc16",
    border: "#1c1917",
  },
  {
    id: "electric-indigo",
    name: "电光靛蓝",
    description: "现代科技感 SaaS 蓝紫",
    primary: "#4f46e5",
    secondary: "#e0e7ff",
    accent: "#06b6d4",
    border: "#0f172a",
  },
  {
    id: "monochrome-ink",
    name: "极简纯墨",
    description: "黑白极简主义对比",
    primary: "#000000",
    secondary: "#e4e4e7",
    accent: "#71717a",
    border: "#000000",
  },
];
