import type { ThemeInspirationPalette, ThemePreset } from "./types";

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "default",
    name: "现代极简",
    englishName: "Mastra Clean",
    category: "modern",
    categoryLabel: "现代极简",
    description: "基于 Mastra 官方设计规范的高性能极简风格，优雅微阴影与多层圆角体系。",
    registrySource: "official",
    styleKey: "default",
    light: {
      background: "#ffffff",
      foreground: "#171717",
      card: "#ffffff",
      cardForeground: "#171717",
      popover: "#ffffff",
      popoverForeground: "#171717",
      primary: "#171717",
      primaryForeground: "#fafafa",
      secondary: "#f5f5f5",
      secondaryForeground: "#171717",
      muted: "#f5f5f5",
      mutedForeground: "#737373",
      accent: "#f5f5f5",
      accentForeground: "#171717",
      destructive: "#dc2626",
      destructiveForeground: "#fafafa",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#a3a3a3",
      sidebar: "#fafafa",
      sidebarForeground: "#171717",
      sidebarPrimary: "#171717",
      sidebarPrimaryForeground: "#fafafa",
      sidebarAccent: "#f5f5f5",
      sidebarAccentForeground: "#171717",
      sidebarBorder: "#e5e5e5",
    },
    dark: {
      background: "#121212",
      foreground: "#fafafa",
      card: "#18181b",
      cardForeground: "#fafafa",
      popover: "#18181b",
      popoverForeground: "#fafafa",
      primary: "#fafafa",
      primaryForeground: "#121212",
      secondary: "#262626",
      secondaryForeground: "#fafafa",
      muted: "#262626",
      mutedForeground: "#a3a3a3",
      accent: "#262626",
      accentForeground: "#fafafa",
      destructive: "#ef4444",
      destructiveForeground: "#fafafa",
      border: "#27272a",
      input: "#27272a",
      ring: "#71717a",
      sidebar: "#18181b",
      sidebarForeground: "#fafafa",
      sidebarPrimary: "#3b82f6",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#27272a",
      sidebarAccentForeground: "#fafafa",
      sidebarBorder: "#27272a",
    },
    geometry: {
      radius: 10,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans:
        'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
      fontMono: '"JetBrains Mono", "SF Mono", Consolas, monospace',
      headingWeight: "600",
      letterSpacing: "-0.015em",
      textTransform: "none",
    },
  },
  {
    id: "boldkit",
    name: "BoldKit 新粗野",
    englishName: "BoldKit Brutalism",
    category: "brutalism",
    categoryLabel: "粗野主义",
    description: "极具视觉张力的新粗野主义体系，以纯黑厚重描边、立体实体硬阴影和高饱和亮橙为代表。",
    registrySource: "@boldkit",
    styleKey: "boldkit",
    light: {
      background: "#fefcf6",
      foreground: "#09090b",
      card: "#ffffff",
      cardForeground: "#09090b",
      popover: "#ffffff",
      popoverForeground: "#09090b",
      primary: "#ff5400",
      primaryForeground: "#ffffff",
      secondary: "#ffe5d0",
      secondaryForeground: "#09090b",
      muted: "#f5eedc",
      mutedForeground: "#52525b",
      accent: "#ffc837",
      accentForeground: "#09090b",
      destructive: "#e11d48",
      destructiveForeground: "#ffffff",
      border: "#09090b",
      input: "#09090b",
      ring: "#ff5400",
      sidebar: "#faf3e0",
      sidebarForeground: "#09090b",
      sidebarPrimary: "#ff5400",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#ffe5d0",
      sidebarAccentForeground: "#09090b",
      sidebarBorder: "#09090b",
    },
    dark: {
      background: "#121214",
      foreground: "#f4f4f5",
      card: "#1a1a1e",
      cardForeground: "#f4f4f5",
      popover: "#1a1a1e",
      popoverForeground: "#f4f4f5",
      primary: "#ff6b2b",
      primaryForeground: "#ffffff",
      secondary: "#27272a",
      secondaryForeground: "#f4f4f5",
      muted: "#1c1c1f",
      mutedForeground: "#a1a1aa",
      accent: "#ffd043",
      accentForeground: "#09090b",
      destructive: "#fb7185",
      destructiveForeground: "#121214",
      border: "#ff6b2b",
      input: "#ff6b2b",
      ring: "#ff6b2b",
      sidebar: "#0b0b0d",
      sidebarForeground: "#f4f4f5",
      sidebarPrimary: "#ff6b2b",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#27272a",
      sidebarAccentForeground: "#f4f4f5",
      sidebarBorder: "#3f3f46",
    },
    geometry: {
      radius: 6,
      borderWidth: 2,
      shadowDepth: 3,
    },
    typography: {
      fontSans: '"Space Grotesk", "Public Sans", "Inter", -apple-system, sans-serif',
      fontMono: '"Space Mono", monospace',
      headingWeight: "800",
      letterSpacing: "-0.03em",
      textTransform: "none",
    },
  },
  {
    id: "neobrutalism",
    name: "NeoBrutalism 经典",
    englishName: "Classic NeoBrutalism",
    category: "brutalism",
    categoryLabel: "粗野主义",
    description:
      "经典新粗野主义，0 弧度锐角几何、2px 纯黑外边框、4px 硬阴影与赛博柠檬黄、霓虹青撞色。",
    registrySource: "@neobrutalism",
    styleKey: "neobrutalism",
    light: {
      background: "#fffdfa",
      foreground: "#000000",
      card: "#ffffff",
      cardForeground: "#000000",
      popover: "#ffffff",
      popoverForeground: "#000000",
      primary: "#facc15",
      primaryForeground: "#000000",
      secondary: "#a5f3fc",
      secondaryForeground: "#000000",
      muted: "#f4f4eb",
      mutedForeground: "#3f3f46",
      accent: "#f472b6",
      accentForeground: "#000000",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#000000",
      input: "#000000",
      ring: "#000000",
      sidebar: "#fdf8e6",
      sidebarForeground: "#000000",
      sidebarPrimary: "#000000",
      sidebarPrimaryForeground: "#facc15",
      sidebarAccent: "#fef08a",
      sidebarAccentForeground: "#000000",
      sidebarBorder: "#000000",
    },
    dark: {
      background: "#09090b",
      foreground: "#ffffff",
      card: "#131316",
      cardForeground: "#ffffff",
      popover: "#131316",
      popoverForeground: "#ffffff",
      primary: "#facc15",
      primaryForeground: "#000000",
      secondary: "#164e63",
      secondaryForeground: "#67e8f9",
      muted: "#18181b",
      mutedForeground: "#a1a1aa",
      accent: "#831843",
      accentForeground: "#f472b6",
      destructive: "#f87171",
      destructiveForeground: "#09090b",
      border: "#facc15",
      input: "#facc15",
      ring: "#facc15",
      sidebar: "#050507",
      sidebarForeground: "#ffffff",
      sidebarPrimary: "#facc15",
      sidebarPrimaryForeground: "#000000",
      sidebarAccent: "#27272a",
      sidebarAccentForeground: "#facc15",
      sidebarBorder: "#3f3f46",
    },
    geometry: {
      radius: 0,
      borderWidth: 2,
      shadowDepth: 4,
    },
    typography: {
      fontSans: '"Space Grotesk", "Public Sans", "Arial Black", -apple-system, sans-serif',
      fontMono: '"Space Mono", monospace',
      headingWeight: "800",
      letterSpacing: "-0.035em",
      textTransform: "none",
    },
  },
  {
    id: "retroui",
    name: "RetroUI 复古粗野",
    englishName: "Retro Modern Brutalism",
    category: "brutalism",
    categoryLabel: "粗野主义",
    description: "融合 90 年代报纸排版与极客终端质感，复古琥珀橙、羊皮纸暖底色与粗粝外框。",
    registrySource: "@retroui",
    styleKey: "retroui",
    light: {
      background: "#faf6ee",
      foreground: "#1c1917",
      card: "#ffffff",
      cardForeground: "#1c1917",
      popover: "#ffffff",
      popoverForeground: "#1c1917",
      primary: "#d97706",
      primaryForeground: "#ffffff",
      secondary: "#e7dfd3",
      secondaryForeground: "#1c1917",
      muted: "#ece5d8",
      mutedForeground: "#78716c",
      accent: "#84cc16",
      accentForeground: "#1c1917",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      border: "#1c1917",
      input: "#1c1917",
      ring: "#d97706",
      sidebar: "#f3ecde",
      sidebarForeground: "#1c1917",
      sidebarPrimary: "#d97706",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e4dac9",
      sidebarAccentForeground: "#1c1917",
      sidebarBorder: "#1c1917",
    },
    dark: {
      background: "#161311",
      foreground: "#faf6ee",
      card: "#201b17",
      cardForeground: "#faf6ee",
      popover: "#201b17",
      popoverForeground: "#faf6ee",
      primary: "#f59e0b",
      primaryForeground: "#161311",
      secondary: "#2a2420",
      secondaryForeground: "#faf6ee",
      muted: "#221c18",
      mutedForeground: "#a8a29e",
      accent: "#a3e635",
      accentForeground: "#161311",
      destructive: "#ef4444",
      destructiveForeground: "#161311",
      border: "#786b59",
      input: "#786b59",
      ring: "#f59e0b",
      sidebar: "#100e0c",
      sidebarForeground: "#faf6ee",
      sidebarPrimary: "#f59e0b",
      sidebarPrimaryForeground: "#161311",
      sidebarAccent: "#241f1a",
      sidebarAccentForeground: "#faf6ee",
      sidebarBorder: "#443b32",
    },
    geometry: {
      radius: 4,
      borderWidth: 2,
      shadowDepth: 3,
    },
    typography: {
      fontSans: '"Bricolage Grotesque Variable", "Plus Jakarta Sans", -apple-system, sans-serif',
      fontMono: '"Space Mono", monospace',
      headingWeight: "700",
      letterSpacing: "-0.02em",
      textTransform: "none",
    },
  },
  {
    id: "saaskit",
    name: "SaaSKit 柔和粗野",
    englishName: "SaaSKit Soft Brutal",
    category: "soft_brutalism",
    categoryLabel: "柔和粗野",
    description: "专为现代化高质感 SaaS 打造的柔和粗野主义，圆润大边角、克制深色轮廓与电光靛蓝。",
    registrySource: "@saaskit",
    styleKey: "saaskit",
    light: {
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      primary: "#4f46e5",
      primaryForeground: "#ffffff",
      secondary: "#e0e7ff",
      secondaryForeground: "#3730a3",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      accent: "#06b6d4",
      accentForeground: "#ffffff",
      destructive: "#e11d48",
      destructiveForeground: "#ffffff",
      border: "#0f172a",
      input: "#0f172a",
      ring: "#4f46e5",
      sidebar: "#f1f5f9",
      sidebarForeground: "#0f172a",
      sidebarPrimary: "#4f46e5",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e2e8f0",
      sidebarAccentForeground: "#0f172a",
      sidebarBorder: "#0f172a",
    },
    dark: {
      background: "#090d16",
      foreground: "#f8fafc",
      card: "#111827",
      cardForeground: "#f8fafc",
      popover: "#111827",
      popoverForeground: "#f8fafc",
      primary: "#6366f1",
      primaryForeground: "#ffffff",
      secondary: "#1e1b4b",
      secondaryForeground: "#e0e7ff",
      muted: "#131b2e",
      mutedForeground: "#94a3b8",
      accent: "#22d3ee",
      accentForeground: "#090d16",
      destructive: "#f43f5e",
      destructiveForeground: "#ffffff",
      border: "#334155",
      input: "#334155",
      ring: "#6366f1",
      sidebar: "#060910",
      sidebarForeground: "#f8fafc",
      sidebarPrimary: "#6366f1",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#1e293b",
      sidebarAccentForeground: "#f8fafc",
      sidebarBorder: "#334155",
    },
    geometry: {
      radius: 10,
      borderWidth: 1.5,
      shadowDepth: 3,
    },
    typography: {
      fontSans: '"Plus Jakarta Sans", "Inter", -apple-system, sans-serif',
      fontMono: '"Space Mono", "SF Mono", monospace',
      headingWeight: "600",
      letterSpacing: "-0.015em",
      textTransform: "none",
    },
  },
  {
    id: "pouf",
    name: "Pouf 黏土拟物",
    englishName: "1st-Pouf Claymorphism",
    category: "clay_glass",
    categoryLabel: "拟物与质感",
    description: "柔和可爱的粉彩 3D 黏土膨胀风格，宛如软垫般的立体触觉、双层内发光与充气软阴影。",
    registrySource: "@1st-pouf",
    styleKey: "pouf",
    light: {
      background: "#f7f3ff",
      foreground: "#2d2244",
      card: "#ffffff",
      cardForeground: "#2d2244",
      popover: "#ffffff",
      popoverForeground: "#2d2244",
      primary: "#8b5cf6",
      primaryForeground: "#ffffff",
      secondary: "#ede9fe",
      secondaryForeground: "#4c1d95",
      muted: "#f3e8ff",
      mutedForeground: "#7e69ab",
      accent: "#fbcfe8",
      accentForeground: "#831843",
      destructive: "#f43f5e",
      destructiveForeground: "#ffffff",
      border: "#e4d4f8",
      input: "#e4d4f8",
      ring: "#8b5cf6",
      sidebar: "#f3edff",
      sidebarForeground: "#2d2244",
      sidebarPrimary: "#8b5cf6",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#ede9fe",
      sidebarAccentForeground: "#4c1d95",
      sidebarBorder: "#e4d4f8",
    },
    dark: {
      background: "#1e192c",
      foreground: "#f5f3ff",
      card: "#27203b",
      cardForeground: "#f5f3ff",
      popover: "#27203b",
      popoverForeground: "#f5f3ff",
      primary: "#a78bfa",
      primaryForeground: "#1e192c",
      secondary: "#382d54",
      secondaryForeground: "#f5f3ff",
      muted: "#382d54",
      mutedForeground: "#b3a4d4",
      accent: "#f472b6",
      accentForeground: "#1e192c",
      destructive: "#fb7185",
      destructiveForeground: "#ffffff",
      border: "#433666",
      input: "#433666",
      ring: "#a78bfa",
      sidebar: "#231c34",
      sidebarForeground: "#f5f3ff",
      sidebarPrimary: "#a78bfa",
      sidebarPrimaryForeground: "#1e192c",
      sidebarAccent: "#382d54",
      sidebarAccentForeground: "#f5f3ff",
      sidebarBorder: "#433666",
    },
    geometry: {
      radius: 18,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans: '"Nunito", "Plus Jakarta Sans", -apple-system, sans-serif',
      fontMono: '"JetBrains Mono", monospace',
      headingWeight: "700",
      letterSpacing: "0.005em",
      textTransform: "none",
    },
  },
  {
    id: "glasscn",
    name: "GlassCN 玻璃拟态",
    englishName: "Glassmorphism UI",
    category: "clay_glass",
    categoryLabel: "拟物与质感",
    description:
      "受 Apple 现代界面启发的半透明玻璃拟态，高饱和亚克力模糊、晶亮边缘微光与空间折射感。",
    registrySource: "@glasscn",
    styleKey: "glasscn",
    light: {
      background: "#f0f4f9",
      foreground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      primary: "#0284c7",
      primaryForeground: "#ffffff",
      secondary: "#e0f2fe",
      secondaryForeground: "#0369a1",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      accent: "#38bdf8",
      accentForeground: "#0c4a6e",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#cbd5e1",
      input: "#cbd5e1",
      ring: "#0284c7",
      sidebar: "#f8fafc",
      sidebarForeground: "#0f172a",
      sidebarPrimary: "#0284c7",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e2e8f0",
      sidebarAccentForeground: "#0f172a",
      sidebarBorder: "#e2e8f0",
    },
    dark: {
      background: "#090d16",
      foreground: "#f8fafc",
      card: "#0f172a",
      popover: "#0f172a",
      popoverForeground: "#f8fafc",
      cardForeground: "#f8fafc",
      primary: "#38bdf8",
      primaryForeground: "#090d16",
      secondary: "#1e293b",
      secondaryForeground: "#f8fafc",
      muted: "#1e293b",
      mutedForeground: "#94a3b8",
      accent: "#0284c7",
      accentForeground: "#ffffff",
      destructive: "#f87171",
      destructiveForeground: "#ffffff",
      border: "#334155",
      input: "#334155",
      ring: "#38bdf8",
      sidebar: "#0b1120",
      sidebarForeground: "#f8fafc",
      sidebarPrimary: "#38bdf8",
      sidebarPrimaryForeground: "#090d16",
      sidebarAccent: "#1e293b",
      sidebarAccentForeground: "#f8fafc",
      sidebarBorder: "#1e293b",
    },
    geometry: {
      radius: 14,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans:
        '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", "Plus Jakarta Sans", "Inter", system-ui, sans-serif',
      fontMono: '"SF Mono", "JetBrains Mono", monospace',
      headingWeight: "600",
      letterSpacing: "-0.02em",
      textTransform: "none",
    },
  },
  {
    id: "einui",
    name: "EinUI 磨砂晶钻",
    englishName: "EinUI Frosted Acrylic",
    category: "clay_glass",
    categoryLabel: "拟物与质感",
    description: "暗黑模式优先的深邃磨砂亚克力玻璃，天鹅绒般细腻雾面、柔和漫反射与冰晶翡翠质感。",
    registrySource: "@einui",
    styleKey: "einui",
    light: {
      background: "#f4f6f8",
      foreground: "#111827",
      card: "#ffffff",
      cardForeground: "#111827",
      popover: "#ffffff",
      popoverForeground: "#111827",
      primary: "#059669",
      primaryForeground: "#ffffff",
      secondary: "#d1fae5",
      secondaryForeground: "#065f46",
      muted: "#e5e7eb",
      mutedForeground: "#6b7280",
      accent: "#10b981",
      accentForeground: "#ffffff",
      destructive: "#e11d48",
      destructiveForeground: "#ffffff",
      border: "#d1d5db",
      input: "#d1d5db",
      ring: "#059669",
      sidebar: "#f9fafb",
      sidebarForeground: "#111827",
      sidebarPrimary: "#059669",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e5e7eb",
      sidebarAccentForeground: "#111827",
      sidebarBorder: "#e5e7eb",
    },
    dark: {
      background: "#061017",
      foreground: "#ecfdf5",
      card: "#0b1a24",
      cardForeground: "#ecfdf5",
      popover: "#0b1a24",
      popoverForeground: "#ecfdf5",
      primary: "#10b981",
      primaryForeground: "#061017",
      secondary: "#132b3c",
      secondaryForeground: "#ecfdf5",
      muted: "#132b3c",
      mutedForeground: "#839ba8",
      accent: "#34d399",
      accentForeground: "#061017",
      destructive: "#fb7185",
      destructiveForeground: "#ffffff",
      border: "#1c3b50",
      input: "#1c3b50",
      ring: "#10b981",
      sidebar: "#08141d",
      sidebarForeground: "#ecfdf5",
      sidebarPrimary: "#10b981",
      sidebarPrimaryForeground: "#061017",
      sidebarAccent: "#132b3c",
      sidebarAccentForeground: "#ecfdf5",
      sidebarBorder: "#1c3b50",
    },
    geometry: {
      radius: 12,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans: '"Plus Jakarta Sans", "Inter", -apple-system, sans-serif',
      fontMono: '"JetBrains Mono", "Fira Code", monospace',
      headingWeight: "600",
      letterSpacing: "-0.01em",
      textTransform: "none",
    },
  },
  {
    id: "sabraman",
    name: "Sabraman 经典拟物",
    englishName: "Sabraman Skeuomorphism",
    category: "clay_glass",
    categoryLabel: "拟物与质感",
    description:
      "致敬经典 UI 的高保真拟物风格，顶部高光倒角、立体渐变浮雕、真实物理按压触感与暖调质感。",
    registrySource: "@sabraman",
    styleKey: "sabraman",
    light: {
      background: "#e9e6df",
      foreground: "#2b2723",
      card: "#fbfaf7",
      cardForeground: "#2b2723",
      popover: "#fbfaf7",
      popoverForeground: "#2b2723",
      primary: "#3b5998",
      primaryForeground: "#ffffff",
      secondary: "#d8d2c4",
      secondaryForeground: "#2b2723",
      muted: "#dfd9cd",
      mutedForeground: "#6e675d",
      accent: "#c29b38",
      accentForeground: "#2b2723",
      destructive: "#c0392b",
      destructiveForeground: "#ffffff",
      border: "#bebaa9",
      input: "#bebaa9",
      ring: "#3b5998",
      sidebar: "#ded8cc",
      sidebarForeground: "#2b2723",
      sidebarPrimary: "#3b5998",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#d0c8ba",
      sidebarAccentForeground: "#2b2723",
      sidebarBorder: "#bebaa9",
    },
    dark: {
      background: "#1c1a17",
      foreground: "#f4eee5",
      card: "#25221e",
      cardForeground: "#f4eee5",
      popover: "#25221e",
      popoverForeground: "#f4eee5",
      primary: "#4d79c7",
      primaryForeground: "#ffffff",
      secondary: "#35302a",
      secondaryForeground: "#f4eee5",
      muted: "#35302a",
      mutedForeground: "#9c9387",
      accent: "#d4af37",
      accentForeground: "#1c1a17",
      destructive: "#e74c3c",
      destructiveForeground: "#ffffff",
      border: "#453e36",
      input: "#453e36",
      ring: "#4d79c7",
      sidebar: "#201d19",
      sidebarForeground: "#f4eee5",
      sidebarPrimary: "#4d79c7",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#35302a",
      sidebarAccentForeground: "#f4eee5",
      sidebarBorder: "#453e36",
    },
    geometry: {
      radius: 8,
      borderWidth: 1,
      shadowDepth: 2,
    },
    typography: {
      fontSans: '"Helvetica Neue", "Lucida Grande", "Segoe UI", Arial, sans-serif',
      fontMono: 'Consolas, "Courier New", monospace',
      headingWeight: "700",
      letterSpacing: "-0.01em",
      textTransform: "none",
    },
  },
  {
    id: "thegridcn",
    name: "TheGridCN 创战纪",
    englishName: "Tron: Ares Cyber Sci-Fi",
    category: "scifi_dark",
    categoryLabel: "科幻与发光",
    description:
      "受《创：战纪》(Tron: Ares) 启发的赛博科幻 HUD 系统，激光赤红与霓虹青蓝、HUD 扫描线与硬核电光发光。",
    registrySource: "@thegridcn",
    styleKey: "thegridcn",
    light: {
      background: "#f0f7fa",
      foreground: "#040d1a",
      card: "#ffffff",
      cardForeground: "#040d1a",
      popover: "#ffffff",
      popoverForeground: "#040d1a",
      primary: "#00bcd4",
      primaryForeground: "#ffffff",
      secondary: "#e0f7fa",
      secondaryForeground: "#006064",
      muted: "#e1f5fe",
      mutedForeground: "#546e7a",
      accent: "#ff003c",
      accentForeground: "#ffffff",
      destructive: "#ff003c",
      destructiveForeground: "#ffffff",
      border: "#00bcd4",
      input: "#00bcd4",
      ring: "#00bcd4",
      sidebar: "#e8f4f8",
      sidebarForeground: "#040d1a",
      sidebarPrimary: "#00bcd4",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#d0edf5",
      sidebarAccentForeground: "#006064",
      sidebarBorder: "#b2ebf2",
    },
    dark: {
      background: "#030712",
      foreground: "#f0fdf4",
      card: "#070e1b",
      cardForeground: "#f0fdf4",
      popover: "#070e1b",
      popoverForeground: "#f0fdf4",
      primary: "#00f0ff",
      primaryForeground: "#030712",
      secondary: "#0f2238",
      secondaryForeground: "#00f0ff",
      muted: "#0a192f",
      mutedForeground: "#7dd3fc",
      accent: "#ff003c",
      accentForeground: "#ffffff",
      destructive: "#ff003c",
      destructiveForeground: "#ffffff",
      border: "#00f0ff",
      input: "#00f0ff",
      ring: "#00f0ff",
      sidebar: "#02050d",
      sidebarForeground: "#f0fdf4",
      sidebarPrimary: "#00f0ff",
      sidebarPrimaryForeground: "#030712",
      sidebarAccent: "#0b1c2e",
      sidebarAccentForeground: "#00f0ff",
      sidebarBorder: "#0e3a5a",
    },
    geometry: {
      radius: 2,
      borderWidth: 1.5,
      shadowDepth: 0,
    },
    typography: {
      fontSans: '"Orbitron", "Rajdhani", "Space Grotesk", sans-serif',
      fontMono: '"Space Mono", monospace',
      headingWeight: "800",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
    },
  },
  {
    id: "gymnopedies",
    name: "Gymnopédies 萨蒂静谧",
    englishName: "Satie Literary Dark Glow",
    category: "scifi_dark",
    categoryLabel: "科幻与发光",
    description:
      "灵感源自埃里克·萨蒂《裸体歌舞》的暗调静谧文学主题，古老衬线排版、烛光微金暖光与沉浸式夜读氛围。",
    registrySource: "@gymnopedies",
    styleKey: "gymnopedies",
    light: {
      background: "#fcfaf7",
      foreground: "#231f1c",
      card: "#ffffff",
      cardForeground: "#231f1c",
      popover: "#ffffff",
      popoverForeground: "#231f1c",
      primary: "#b8860b",
      primaryForeground: "#ffffff",
      secondary: "#f5ede0",
      secondaryForeground: "#231f1c",
      muted: "#f2ebe0",
      mutedForeground: "#786d63",
      accent: "#c9933e",
      accentForeground: "#ffffff",
      destructive: "#9e2a2b",
      destructiveForeground: "#ffffff",
      border: "#dfd5c4",
      input: "#dfd5c4",
      ring: "#b8860b",
      sidebar: "#f7f1e6",
      sidebarForeground: "#231f1c",
      sidebarPrimary: "#b8860b",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#eee4d4",
      sidebarAccentForeground: "#231f1c",
      sidebarBorder: "#dfd5c4",
    },
    dark: {
      background: "#0d0b0a",
      foreground: "#f4ede4",
      card: "#151210",
      cardForeground: "#f4ede4",
      popover: "#151210",
      popoverForeground: "#f4ede4",
      primary: "#e2a855",
      primaryForeground: "#0d0b0a",
      secondary: "#241e1b",
      secondaryForeground: "#f4ede4",
      muted: "#211c19",
      mutedForeground: "#a3978c",
      accent: "#f3b768",
      accentForeground: "#0d0b0a",
      destructive: "#e57373",
      destructiveForeground: "#0d0b0a",
      border: "#3a322c",
      input: "#3a322c",
      ring: "#e2a855",
      sidebar: "#090807",
      sidebarForeground: "#f4ede4",
      sidebarPrimary: "#e2a855",
      sidebarPrimaryForeground: "#0d0b0a",
      sidebarAccent: "#1c1815",
      sidebarAccentForeground: "#f4ede4",
      sidebarBorder: "#2e2722",
    },
    geometry: {
      radius: 6,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans: '"Cormorant Garamond", "Cinzel", Georgia, serif',
      fontMono: '"JetBrains Mono", monospace',
      headingWeight: "600",
      letterSpacing: "0.02em",
      textTransform: "none",
    },
  },
  {
    id: "atroui",
    name: "AtroUI 深空霓虹",
    englishName: "AtroUI Cyberpunk Neon",
    category: "scifi_dark",
    categoryLabel: "科幻与发光",
    description: "暗黑模式优先的极客沉浸式霓虹，深空黑曜石底色、电光激光紫与强自发光边框。",
    registrySource: "@atroui",
    styleKey: "atroui",
    light: {
      background: "#faf7fe",
      foreground: "#140924",
      card: "#ffffff",
      cardForeground: "#140924",
      popover: "#ffffff",
      popoverForeground: "#140924",
      primary: "#9333ea",
      primaryForeground: "#ffffff",
      secondary: "#f3e8ff",
      secondaryForeground: "#581c87",
      muted: "#f5f3ff",
      mutedForeground: "#6b7280",
      accent: "#f43f5e",
      accentForeground: "#ffffff",
      destructive: "#e11d48",
      destructiveForeground: "#ffffff",
      border: "#e9d5ff",
      input: "#e9d5ff",
      ring: "#9333ea",
      sidebar: "#f5edff",
      sidebarForeground: "#140924",
      sidebarPrimary: "#9333ea",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#edd9ff",
      sidebarAccentForeground: "#581c87",
      sidebarBorder: "#e9d5ff",
    },
    dark: {
      background: "#07050d",
      foreground: "#faf5ff",
      card: "#100a1c",
      cardForeground: "#faf5ff",
      popover: "#100a1c",
      popoverForeground: "#faf5ff",
      primary: "#c084fc",
      primaryForeground: "#07050d",
      secondary: "#23153c",
      secondaryForeground: "#faf5ff",
      muted: "#1c1130",
      mutedForeground: "#a892c7",
      accent: "#f43f5e",
      accentForeground: "#ffffff",
      destructive: "#fb7185",
      destructiveForeground: "#ffffff",
      border: "#3b1d6e",
      input: "#3b1d6e",
      ring: "#c084fc",
      sidebar: "#05030a",
      sidebarForeground: "#faf5ff",
      sidebarPrimary: "#c084fc",
      sidebarPrimaryForeground: "#07050d",
      sidebarAccent: "#1a0f2d",
      sidebarAccentForeground: "#faf5ff",
      sidebarBorder: "#2a154e",
    },
    geometry: {
      radius: 8,
      borderWidth: 1.5,
      shadowDepth: 0,
    },
    typography: {
      fontSans: '"Plus Jakarta Sans", "Inter", -apple-system, sans-serif',
      fontMono: '"JetBrains Mono", monospace',
      headingWeight: "700",
      letterSpacing: "-0.02em",
      textTransform: "none",
    },
  },
  {
    id: "usva",
    name: "Usva 极夜大气",
    englishName: "Usva Nordic Mist Atmosphere",
    category: "scifi_dark",
    categoryLabel: "科幻与发光",
    description: "芬兰自然哲学与极夜极光漫反射设计系统，薄雾微光扩散、极客紧凑机能与有机空间质感。",
    registrySource: "@usva",
    styleKey: "usva",
    light: {
      background: "#f1f6f8",
      foreground: "#0a1924",
      card: "#ffffff",
      cardForeground: "#0a1924",
      popover: "#ffffff",
      popoverForeground: "#0a1924",
      primary: "#0d9488",
      primaryForeground: "#ffffff",
      secondary: "#ccfbf1",
      secondaryForeground: "#115e59",
      muted: "#e6eff2",
      mutedForeground: "#527389",
      accent: "#0284c7",
      accentForeground: "#ffffff",
      destructive: "#e11d48",
      destructiveForeground: "#ffffff",
      border: "#cbd5e1",
      input: "#cbd5e1",
      ring: "#0d9488",
      sidebar: "#eef5f8",
      sidebarForeground: "#0a1924",
      sidebarPrimary: "#0d9488",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e2eef2",
      sidebarAccentForeground: "#115e59",
      sidebarBorder: "#cbd5e1",
    },
    dark: {
      background: "#060b11",
      foreground: "#f0fdfa",
      card: "#0c1520",
      cardForeground: "#f0fdfa",
      popover: "#0c1520",
      popoverForeground: "#f0fdfa",
      primary: "#2dd4bf",
      primaryForeground: "#060b11",
      secondary: "#132638",
      secondaryForeground: "#f0fdfa",
      muted: "#112030",
      mutedForeground: "#7ea1b8",
      accent: "#38bdf8",
      accentForeground: "#060b11",
      destructive: "#fb7185",
      destructiveForeground: "#ffffff",
      border: "#1a344d",
      input: "#1a344d",
      ring: "#2dd4bf",
      sidebar: "#04070c",
      sidebarForeground: "#f0fdfa",
      sidebarPrimary: "#2dd4bf",
      sidebarPrimaryForeground: "#060b11",
      sidebarAccent: "#0f1d2b",
      sidebarAccentForeground: "#f0fdfa",
      sidebarBorder: "#14293c",
    },
    geometry: {
      radius: 12,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans: '"Inter", "Geist", "Plus Jakarta Sans", sans-serif',
      fontMono: '"Geist Mono", "SF Mono", monospace',
      headingWeight: "600",
      letterSpacing: "-0.015em",
      textTransform: "none",
    },
  },
  {
    id: "8bitcn",
    name: "8bitCN 像素复古",
    englishName: "8-Bit Retro Gaming",
    category: "pixel_retro",
    categoryLabel: "像素与游戏",
    description: "经典的 8-bit FC/NES 像素复古风格，台阶状硬阴影、粗像素边框与街机怀旧质感。",
    registrySource: "@8bitcn",
    styleKey: "8bitcn",
    light: {
      background: "#f4f4f4",
      foreground: "#111111",
      card: "#ffffff",
      cardForeground: "#111111",
      popover: "#ffffff",
      popoverForeground: "#111111",
      primary: "#e60012",
      primaryForeground: "#ffffff",
      secondary: "#e5e5e5",
      secondaryForeground: "#111111",
      muted: "#eaeaea",
      mutedForeground: "#666666",
      accent: "#f59e0b",
      accentForeground: "#111111",
      destructive: "#e60012",
      destructiveForeground: "#ffffff",
      border: "#000000",
      input: "#000000",
      ring: "#e60012",
      sidebar: "#ebebeb",
      sidebarForeground: "#111111",
      sidebarPrimary: "#e60012",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#dedede",
      sidebarAccentForeground: "#111111",
      sidebarBorder: "#000000",
    },
    dark: {
      background: "#181818",
      foreground: "#f4f4f4",
      card: "#242424",
      cardForeground: "#f4f4f4",
      popover: "#242424",
      popoverForeground: "#f4f4f4",
      primary: "#ff2a3a",
      primaryForeground: "#ffffff",
      secondary: "#333333",
      secondaryForeground: "#f4f4f4",
      muted: "#2e2e2e",
      mutedForeground: "#aaaaaa",
      accent: "#fbbf24",
      accentForeground: "#181818",
      destructive: "#ff2a3a",
      destructiveForeground: "#ffffff",
      border: "#000000",
      input: "#444444",
      ring: "#ff2a3a",
      sidebar: "#121212",
      sidebarForeground: "#f4f4f4",
      sidebarPrimary: "#ff2a3a",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#262626",
      sidebarAccentForeground: "#f4f4f4",
      sidebarBorder: "#000000",
    },
    geometry: {
      radius: 0,
      borderWidth: 2,
      shadowDepth: 3,
    },
    typography: {
      fontSans: '"Silkscreen", "Press Start 2P", "Space Mono", monospace',
      fontMono: '"Space Mono", "Press Start 2P", monospace',
      headingWeight: "700",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
    },
  },
  {
    id: "pixelact",
    name: "Pixelact 像素艺术",
    englishName: "Pixelact Playful Art",
    category: "pixel_retro",
    categoryLabel: "像素与游戏",
    description:
      "俏皮活泼的像素艺术与 RPG 游戏化设计语言，马赛克边框、游戏糖果色系与像素动态交互。",
    registrySource: "@pixelact-ui",
    styleKey: "pixelact",
    light: {
      background: "#fbf7ee",
      foreground: "#2b2038",
      card: "#ffffff",
      cardForeground: "#2b2038",
      popover: "#ffffff",
      popoverForeground: "#2b2038",
      primary: "#10b981",
      primaryForeground: "#ffffff",
      secondary: "#fef3c7",
      secondaryForeground: "#2b2038",
      muted: "#f3ede0",
      mutedForeground: "#756a85",
      accent: "#ec4899",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#2b2038",
      input: "#2b2038",
      ring: "#10b981",
      sidebar: "#f4ede0",
      sidebarForeground: "#2b2038",
      sidebarPrimary: "#10b981",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e8decc",
      sidebarAccentForeground: "#2b2038",
      sidebarBorder: "#2b2038",
    },
    dark: {
      background: "#181424",
      foreground: "#fbf7ee",
      card: "#221c33",
      cardForeground: "#fbf7ee",
      popover: "#221c33",
      popoverForeground: "#fbf7ee",
      primary: "#34d399",
      primaryForeground: "#181424",
      secondary: "#352b4d",
      secondaryForeground: "#fbf7ee",
      muted: "#2b233e",
      mutedForeground: "#a89ec0",
      accent: "#f472b6",
      accentForeground: "#181424",
      destructive: "#f87171",
      destructiveForeground: "#181424",
      border: "#3f335c",
      input: "#3f335c",
      ring: "#34d399",
      sidebar: "#13101c",
      sidebarForeground: "#fbf7ee",
      sidebarPrimary: "#34d399",
      sidebarPrimaryForeground: "#181424",
      sidebarAccent: "#241d36",
      sidebarAccentForeground: "#fbf7ee",
      sidebarBorder: "#3f335c",
    },
    geometry: {
      radius: 0,
      borderWidth: 2,
      shadowDepth: 2,
    },
    typography: {
      fontSans: '"VT323", "Silkscreen", "Space Mono", monospace',
      fontMono: '"VT323", "Space Mono", monospace',
      headingWeight: "700",
      letterSpacing: "0.04em",
      textTransform: "none",
    },
  },
  {
    id: "washiveil",
    name: "WashiVeil 和纸轻纱",
    englishName: "Washi Veil Oriental Aesthetics",
    category: "oriental_desktop",
    categoryLabel: "东方与桌面",
    description: "“和纸打底，轻纱覆盖，三层底光”，极具东方水墨禅意的中日文排版体系与和纸微透质感。",
    registrySource: "@washiveil",
    styleKey: "washiveil",
    light: {
      background: "#f8f5ee",
      foreground: "#28231d",
      card: "#ffffff",
      cardForeground: "#28231d",
      popover: "#ffffff",
      popoverForeground: "#28231d",
      primary: "#8b572a",
      primaryForeground: "#ffffff",
      secondary: "#eee7d8",
      secondaryForeground: "#28231d",
      muted: "#ece5d5",
      mutedForeground: "#7a7062",
      accent: "#c23531",
      accentForeground: "#ffffff",
      destructive: "#c23531",
      destructiveForeground: "#ffffff",
      border: "#ded5c2",
      input: "#ded5c2",
      ring: "#8b572a",
      sidebar: "#f2ece0",
      sidebarForeground: "#28231d",
      sidebarPrimary: "#8b572a",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e5dcce",
      sidebarAccentForeground: "#28231d",
      sidebarBorder: "#ded5c2",
    },
    dark: {
      background: "#141210",
      foreground: "#f5efe4",
      card: "#1e1a16",
      cardForeground: "#f5efe4",
      popover: "#1e1a16",
      popoverForeground: "#f5efe4",
      primary: "#d4a373",
      primaryForeground: "#141210",
      secondary: "#26211c",
      secondaryForeground: "#f5efe4",
      muted: "#221e1a",
      mutedForeground: "#9c9180",
      accent: "#e05a47",
      accentForeground: "#ffffff",
      destructive: "#e05a47",
      destructiveForeground: "#ffffff",
      border: "#383129",
      input: "#383129",
      ring: "#d4a373",
      sidebar: "#0d0c0a",
      sidebarForeground: "#f5efe4",
      sidebarPrimary: "#d4a373",
      sidebarPrimaryForeground: "#141210",
      sidebarAccent: "#1a1613",
      sidebarAccentForeground: "#f5efe4",
      sidebarBorder: "#2a241e",
    },
    geometry: {
      radius: 6,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans:
        '"Noto Serif SC Variable", "Shippori Mincho", "Songti SC", "Cormorant Garamond", serif',
      fontMono: '"JetBrains Mono", monospace',
      headingWeight: "600",
      letterSpacing: "0.06em",
      textTransform: "none",
    },
  },
  {
    id: "whiskeyjack",
    name: "Whiskeyjack 桌面枢纽",
    englishName: "Whiskeyjack Desktop Hub",
    category: "oriental_desktop",
    categoryLabel: "东方与桌面",
    description:
      "为跨端桌面软件 (Tauri/Electron) 打造的现代流线视觉系统，Metro 风格枢纽导航、磨砂操作条与紧凑桌面机能。",
    registrySource: "@whiskeyjack",
    styleKey: "whiskeyjack",
    light: {
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      primary: "#0284c7",
      primaryForeground: "#ffffff",
      secondary: "#f1f5f9",
      secondaryForeground: "#0f172a",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      accent: "#6366f1",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#0284c7",
      sidebar: "#f1f5f9",
      sidebarForeground: "#0f172a",
      sidebarPrimary: "#0284c7",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e2e8f0",
      sidebarAccentForeground: "#0f172a",
      sidebarBorder: "#e2e8f0",
    },
    dark: {
      background: "#090d16",
      foreground: "#f8fafc",
      card: "#0f172a",
      cardForeground: "#f8fafc",
      popover: "#0f172a",
      popoverForeground: "#f8fafc",
      primary: "#38bdf8",
      primaryForeground: "#090d16",
      secondary: "#1e293b",
      secondaryForeground: "#f8fafc",
      muted: "#172033",
      mutedForeground: "#94a3b8",
      accent: "#818cf8",
      accentForeground: "#090d16",
      destructive: "#f87171",
      destructiveForeground: "#090d16",
      border: "#1e293b",
      input: "#1e293b",
      ring: "#38bdf8",
      sidebar: "#060910",
      sidebarForeground: "#f8fafc",
      sidebarPrimary: "#38bdf8",
      sidebarPrimaryForeground: "#090d16",
      sidebarAccent: "#131b2e",
      sidebarAccentForeground: "#f8fafc",
      sidebarBorder: "#172033",
    },
    geometry: {
      radius: 6,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans: 'system-ui, -apple-system, "Segoe UI", "Inter", sans-serif',
      fontMono: '"SF Mono", "JetBrains Mono", monospace',
      headingWeight: "600",
      letterSpacing: "-0.015em",
      textTransform: "none",
    },
  },
  {
    id: "motion",
    name: "动效流光",
    englishName: "Motion Flow",
    category: "modern",
    categoryLabel: "动效主导",
    description:
      "以 Magic UI 动效语言为核心的现代主题：极光渐变环境光、弹性过渡曲线，与光效/粒子组件深度联动。",
    registrySource: "@magicui",
    styleKey: "motion",
    light: {
      background: "#fafafa",
      foreground: "#09090b",
      card: "#ffffff",
      cardForeground: "#09090b",
      popover: "#ffffff",
      popoverForeground: "#09090b",
      primary: "#7c3aed",
      primaryForeground: "#ffffff",
      secondary: "#f4f4f5",
      secondaryForeground: "#18181b",
      muted: "#f4f4f5",
      mutedForeground: "#71717a",
      accent: "#8b5cf6",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#e4e4e7",
      input: "#e4e4e7",
      ring: "#7c3aed",
      sidebar: "#f8f7fc",
      sidebarForeground: "#18181b",
      sidebarPrimary: "#7c3aed",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#ededf6",
      sidebarAccentForeground: "#18181b",
      sidebarBorder: "#e4e4e7",
    },
    dark: {
      background: "#08070d",
      foreground: "#f4f4f5",
      card: "#0f0e17",
      cardForeground: "#f4f4f5",
      popover: "#0f0e17",
      popoverForeground: "#f4f4f5",
      primary: "#a78bfa",
      primaryForeground: "#0f0e17",
      secondary: "#1c1a27",
      secondaryForeground: "#f4f4f5",
      muted: "#171522",
      mutedForeground: "#a1a1aa",
      accent: "#fe8fb5",
      accentForeground: "#0f0e17",
      destructive: "#f87171",
      destructiveForeground: "#0f0e17",
      border: "#262338",
      input: "#262338",
      ring: "#a78bfa",
      sidebar: "#060509",
      sidebarForeground: "#f4f4f5",
      sidebarPrimary: "#a78bfa",
      sidebarPrimaryForeground: "#0f0e17",
      sidebarAccent: "#1c1a27",
      sidebarAccentForeground: "#f4f4f5",
      sidebarBorder: "#262338",
    },
    geometry: {
      radius: 12,
      borderWidth: 1,
      shadowDepth: 0,
    },
    typography: {
      fontSans: '"Inter", "Geist", "Plus Jakarta Sans", sans-serif',
      fontMono: '"JetBrains Mono", monospace',
      headingWeight: "700",
      letterSpacing: "-0.02em",
      textTransform: "none",
    },
  },
];

export const THEME_INSPIRATIONS: ThemeInspirationPalette[] = [
  {
    id: "cyber-yellow",
    name: "赛博柠檬",
    description: "纯黑边框与明烈电光黄",
    primary: "#facc15",
    secondary: "#fef08a",
    accent: "#38bdf8",
    border: "#000000",
  },
  {
    id: "blaze-orange",
    name: "烈焰赤橙",
    description: "高张力活力热烈橙",
    primary: "#ff5400",
    secondary: "#ffe5d0",
    accent: "#ffc837",
    border: "#09090b",
  },
  {
    id: "neon-pink",
    name: "泡泡糖粉",
    description: "潮酷活泼的霓虹桃粉",
    primary: "#f43f5e",
    secondary: "#fce7f3",
    accent: "#a855f7",
    border: "#000000",
  },
  {
    id: "terminal-green",
    name: "极客荧绿",
    description: "黑客复古终端荧光绿",
    primary: "#22c55e",
    secondary: "#dcfce7",
    accent: "#06b6d4",
    border: "#09090b",
  },
  {
    id: "tron-ares",
    name: "创·战纪",
    description: "Tron: Ares 激光赤红与青蓝",
    primary: "#00f0ff",
    secondary: "#0f2238",
    accent: "#ff003c",
    border: "#00f0ff",
  },
  {
    id: "famicom-red",
    name: "红白机像素",
    description: "FC红白机红白撞色与金币黄",
    primary: "#e60012",
    secondary: "#e5e5e5",
    accent: "#f59e0b",
    border: "#000000",
  },
  {
    id: "washi-tea",
    name: "和风古木",
    description: "和纸打底黄栌染与深绯",
    primary: "#8b572a",
    secondary: "#eee7d8",
    accent: "#c23531",
    border: "#ded5c2",
  },
  {
    id: "desktop-slate",
    name: "桌面流线",
    description: "现代 Fluent 冰蓝与板岩灰",
    primary: "#0284c7",
    secondary: "#f1f5f9",
    accent: "#6366f1",
    border: "#e2e8f0",
  },
  {
    id: "candle-amber",
    name: "萨蒂烛光",
    description: "静谧夜读暗金与暖琥珀",
    primary: "#e2a855",
    secondary: "#241e1b",
    accent: "#f3b768",
    border: "#3a322c",
  },
  {
    id: "cyber-purple",
    name: "深空霓虹",
    description: "深空黑曜石与电光紫粉",
    primary: "#c084fc",
    secondary: "#23153c",
    accent: "#f43f5e",
    border: "#3b1d6e",
  },
  {
    id: "nordic-aurora",
    name: "北欧极光",
    description: "极夜极光薄雾与冰川青",
    primary: "#2dd4bf",
    secondary: "#132638",
    accent: "#38bdf8",
    border: "#1a344d",
  },
  {
    id: "pastel-clay",
    name: "粉彩黏土",
    description: "柔和治愈系薰衣草紫与棉花糖粉",
    primary: "#8b5cf6",
    secondary: "#ede9fe",
    accent: "#fbcfe8",
    border: "#e4d4f8",
  },
  {
    id: "crystal-ice",
    name: "冰晶极光",
    description: "高透亮晶莹 Apple 玻璃海蓝",
    primary: "#0284c7",
    secondary: "#e0f2fe",
    accent: "#38bdf8",
    border: "#cbd5e1",
  },
  {
    id: "emerald-glass",
    name: "翡翠晶钻",
    description: "磨砂深邃翡翠绿与薄荷青",
    primary: "#059669",
    secondary: "#d1fae5",
    accent: "#10b981",
    border: "#d1d5db",
  },
  {
    id: "classic-leather",
    name: "复古皮质",
    description: "经典拟物高光倒角与暖木棕",
    primary: "#3b5998",
    secondary: "#d8d2c4",
    accent: "#c29b38",
    border: "#bebaa9",
  },
  {
    id: "electric-indigo",
    name: "电光靛蓝",
    description: "现代科技感 SaaS 蓝紫",
    primary: "#4f46e5",
    secondary: "#e0e7ff",
    accent: "#06b6d4",
    border: "#0f172a",
  },
  {
    id: "monochrome-ink",
    name: "极简纯墨",
    description: "黑白极简主义对比",
    primary: "#000000",
    secondary: "#e4e4e7",
    accent: "#71717a",
    border: "#000000",
  },
];
